# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f848642e90f64cf251378ae7c2a6a37e2a563bfe80102a3ddf0e1a4d522faa8a3e834400a194f5cba5c5a0f7ef1d4e5699c621d57b4f2410230e01d4203d3180

test:
  secret_key_base: 0506b2f62b9bc1dd8566b43258bc055af3a11328fc4db0a4d0320572b71c5d45bd75013c62732e3ce9071ad0b065b678618e026d2563176d6f09d3de624a6542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
